version: "3"
services:
  backend:
    image: surendergupta/backend-image
    ports:
      - "5000:5000"
#    depends_on:
#      - mongo
  frontend:
    image: surendergupta/frontend-image
    ports:
      - "3000:3000"
    depends_on:
      - backend
